# backend-node/Dockerfile.prod
FROM node:20-alpine AS deps
WORKDIR /app
COPY backend-node/package*.json ./
RUN npm install --only=production

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY backend-node/package*.json ./
COPY backend-node/src ./src
COPY backend-node/entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh
EXPOSE 3001
ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "run", "start"]